name: Publish Package

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

env:
  python-version: 3.13

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
          ref: ${{ inputs.version }}

      - name: Set up Python ${{ env.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ env.python-version }}

      - name: Install Dependencies
        run: uv sync --locked

      - name: Publish
        run: |
          uv build
          uv publish --token ${{ secrets.UV_PUBLISH_TOKEN }}
