name: Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  release:
    name: Create Release from Tag
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ inputs.version }}

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.version }}
          # tag: ${{ github.ref_name }}
        run: |
          GIT_LOG=$(git log $(git describe --tags --abbrev=0)..HEAD --oneline --pretty=%s)
          CONTAINER_ID=$(gh api /user/packages/container/{repo}/versions|jq -r --arg tag ${tag} '.[] | select(.metadata.container.tags[] == $tag) | .id')
          CONTAINER_URL="https://github.com/${{ github.repository }}/pkgs/container/${{ github.event.repository.name }}/${CONTAINER_ID}?tag=${tag}"
          DOCKER_PULL="docker pull ghcr.io/${{ github.repository }}:${{ inputs.version }}"
          PYPI_URL="https://pypi.org/project/${{ github.event.repository.name }}/"
          NOTE=$(echo -e "${GIT_LOG}\n\n- [PyPI](${PYPI_URL})\n- [${{ github.event.repository.name }}:${{ inputs.version }}](${CONTAINER_URL})\n\`\`\`shell\n${DOCKER_PULL}\n\`\`\`")
          gh release create ${tag} --title "v${tag}" --notes "$NOTE"
